include mk/var.mk
include mk/dirs.mk
include mk/tool.mk
include mk/cross.mk
include mk/src.mk
include mk/cfg.mk
include mk/all.mk
include mk/format.mk
include mk/rule.mk
include mk/doc.mk
include mk/install.mk
include mk/merge.mk
